Vagrant::Config.run do |config|

  config.vm.box = "centos56"
  config.vm.box_url= "http://yum.mnxsolutions.com/vagrant/centos_56_32.box"
  # config.vm.boot_mode = :gui

  config.vbguest.auto_update = false

  # config.vm.network :hostonly, "192.168.33.10"
  # config.vm.network :bridged
  # config.vm.forward_port 8649, 8650 

  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.vm.provision :puppet,
    :facter => {
      "stage" => "PROD",
      "role"  => "respub"
     }, :options => ["--debug"] do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "modules"
  end

end
