# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define "raring", primary: true do |raring|
    raring.vm.box = "raring64"  # 13.04
    raring.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
    raring.vm.network :private_network, ip: "192.168.0.105"
    raring.vm.provision :shell, :path => "scripts/ubuntu.sh"
  end

  config.vm.define "wheezy" do |wheezy|
    wheezy.vm.box = "wheezy64"  # debian 7.0
    wheezy.vm.box_url = "https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box"
    wheezy.vm.network :private_network, ip: "192.168.0.106"
    wheezy.vm.provision :shell, :path => "scripts/debian.sh"
  end

  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "centos6"
    centos6.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
    centos6.vm.network :private_network, ip: "192.168.0.107"
    centos6.vm.provision :shell, :path => "scripts/centos.sh"
  end

end
