Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

  # config.vm.boot_mode = :gui

  config.vm.network :hostonly, "172.16.0.12", :netmask => "255.255.0.0"
  config.vm.network :bridged

  # config.vm.forward_port 80, 8080
  # config.vm.forward_port 8649, 10649

  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  # config.vm.provision :puppet, :options => ["--debug"] do |puppet|
  #   puppet.manifests_path = "."
  #   puppet.manifest_file  = "site.pp"
  #   puppet.module_path    = "modules"
  # end

end
