Vagrant::Config.run do |config|

  config.vm.box = "squeeze64"
  # config.vm.boot_mode = :gui
  # config.vbguest.auto_update = true

  # config.vm.network :hostonly, "192.168.33.10"
  config.vm.network :bridged
  # config.vm.forward_port 80, 8080

  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.vm.provision :shell, :path => "setup.sh"

end
