
Vagrant.configure("2") do |config|

  config.vm.box = "precise64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.network :private_network, ip: "172.16.0.2"
  # config.vm.network :public_network

  # Give the VM more memory.
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1512"]
  end

  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provision :shell, :path => "setup.sh"

end
