
Vagrant.configure("2") do |config|

  config.vm.box = "wheezy64"  # debian 7.0
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box"
  config.vm.network :private_network, ip: "192.168.0.123"
  config.vm.provision :shell, :path => "setup.sh"

end
