Vagrant::Config.run do |config|

  config.vm.box = "centos6"
  config.vm.box_url= "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
  # config.vm.boot_mode = :gui

  config.vbguest.auto_update = false

  # config.vm.network :hostonly, "192.168.33.10"
  # config.vm.network :bridged
  # config.vm.forward_port 8649, 8650 

  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.vm.provision :puppet,
    :facter => {
      "role"                            => "frontend-front",
      "int_service_domain"              => "gudev.gnl",
      "ec2_instance_id"                 => "i-000000",
      "ec2_local_ipv4"                  => "10.1.1.1",
      "ec2_placement_availability_zone" => "eu-west-1a"
    },
    :options => [ 
      "--debug"
    ] do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "modules"
  end

end
