# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box"

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :openstack do |os|

    os.username     = "#{ENV['OS_USERNAME']}"
    os.api_key      = "#{ENV['OS_PASSWORD']}"
    os.endpoint     = "#{ENV['OS_AUTH_URL']}/tokens"
    os.tenant       = "#{ENV['OS_TENANT_NAME']}"

    os.flavor       = "m1.tiny"
    os.image        = "ubuntu-raring-13.04-amd64-vagrant"

    # os.keypair_name = "bootstrap"
    os.keypair_name = "nsatterl-dev1"
    os.ssh_username = "vagrant"

    os.security_groups = ['default']
    os.network         = "DC1_DEV_OSTK_INTERNAL"

    # os.address_id  = "YOUR ADDRESS ID"              # optional (`network` above has higher precedence)
    # os.metadata  = {"key" => "value"}                      # optional
    # os.user_data = "#cloud-config\nmanage_etc_hosts: True" # optional
    # os.availability_zone  = "az0001"           # optional
    # os.floating_ip        = "33.33.33.33"      # optional (The floating IP to assign for this instance)

  end
end

